#!/usr/bin/env bash
# =============================================================================
# sync-ai-configs.sh
#
# Reads from AI/rules/, AI/agents/, AI/skills/ and generates configuration
# files for each supported AI tool.
#
# Supported targets:
#   - Cline           →  .clinerules  (auto-loaded every session)
#   - Claude          →  .claude/CLAUDE.md
#   - Gemini CLI      →  .gemini/GEMINI.md
#   - GitHub Copilot  →  .github/copilot-instructions.md
#   - Cursor          →  .cursorrules
#   - OpenAI Codex    →  AGENTS.md (root)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AI_DIR="$ROOT_DIR/AI"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

separator() {
  echo ""
  echo "---"
  echo ""
}

# Concatenate all markdown files in a directory (sorted), with headers
concat_dir() {
  local dir="$1"
  local section_label="$2"

  if [ ! -d "$dir" ]; then
    return
  fi

  local files
  files=$(find "$dir" -maxdepth 1 -name "*.md" | sort)

  if [ -z "$files" ]; then
    return
  fi

  echo "# $section_label"
  echo ""

  for file in $files; do
    cat "$file"
    echo ""
    separator
  done
}

# Build the full combined content from AI/
build_content() {
  local tool_name="$1"

  echo "<!-- Generated by scripts/sync-ai-configs.sh — edit files in AI/ not here -->"
  echo "<!-- Tool: $tool_name | Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ') -->"
  echo ""

  concat_dir "$AI_DIR/rules"  "Rules"
  concat_dir "$AI_DIR/agents" "Agents"
  concat_dir "$AI_DIR/skills" "Skills"
}

# Write content to a file, creating directories as needed
write_config() {
  local target="$1"
  local tool_name="$2"

  mkdir -p "$(dirname "$target")"
  build_content "$tool_name" > "$target"
  echo "  ✓ $target"
}

# ---------------------------------------------------------------------------
# Generate per-tool configs
# ---------------------------------------------------------------------------

echo "🔄 Syncing AI configs from AI/ ..."
echo ""

# Cline (.clinerules — loaded automatically at the start of every Cline session)
write_config "$ROOT_DIR/.clinerules" "Cline"

# Claude (legacy path kept for compatibility)
write_config "$ROOT_DIR/.claude/CLAUDE.md" "Claude"

# Gemini CLI
write_config "$ROOT_DIR/.gemini/GEMINI.md" "Gemini CLI"

# GitHub Copilot
write_config "$ROOT_DIR/.github/copilot-instructions.md" "GitHub Copilot"

# Cursor
write_config "$ROOT_DIR/.cursorrules" "Cursor"

# OpenAI Codex (root-level AGENTS.md)
write_config "$ROOT_DIR/AGENTS.md" "OpenAI Codex"

echo ""
echo "✅ Done. All AI tool configs are up to date."
echo ""
echo "Tip: Run 'make sync-ai' or 'bash scripts/sync-ai-configs.sh' after"
echo "     editing any file in AI/rules/, AI/agents/, or AI/skills/"